### ISSUE TITLE
Operators, block arguments not highlighted

### ISSUE THREAD

**Issue by ron-wolf** [crystal-lang-tools/language-crystal#18]
This includes `.`, `,`, `|`, `key`, and `val` in the screenshot below. There may be some coupling with the particular theme, so I guess it’s worth noting that I’m using [Material Syntax](https://atom.io/themes/material-syntax).

![Ruby vs. Crystal highlighting in Atom](https://cloud.githubusercontent.com/assets/7342888/26758808/d58e1b1a-48b7-11e7-9f32-e3f08ee5ed80.png)

**Comment by faustinoaq** [comment]
@ron-wolf Do you still have this issue?
