### ISSUE TITLE
Highlighting issue with `?` methods?

### ISSUE THREAD

**Issue by rmosolgo** [crystal-lang-tools/language-crystal#3]
Hi, 

Thanks for this great package! I noticed one case where the highlighting gets confused, I thought I'd share it:

![image](https://cloud.githubusercontent.com/assets/2231765/11452449/b9b5eb54-95b5-11e5-94a9-a101ab1e0fdc.png)

I think it's the `]?)` that gets it.

**Comment by keplersj** [comment]
d'oh! I'll figure that out.

Thanks!

**Comment by keplersj** [comment]
Sorry I hadn't gotten to this yet. I just did some experimentation and this is actually a bug which originate with this package's origin in Ruby. I'll rewrite the numeric regex so that this should work.

**Comment by keplersj** [comment]
Fixed!

![screen shot 2016-05-07 at 8 46 01 pm](https://cloud.githubusercontent.com/assets/594124/15095721/c86a470e-1494-11e6-905f-1a38b255c275.png)
